#!/bin/bash
echo "ALX"
echo "ALX"
mkdir bash c js
touch c/c_is_fun.c js/main.js js/index.js
echo '#!/bin/bash' > bash/alx
echo 'echo "ALX"' >> bash/alx
echo '#!/bin/bash' > bash/school
echo 'echo "School"' >> bash/school
git add .



git commit -m "Starting to code today, so cool"
git commit -m "Starting to code today, so cool"
git push
